### ISSUE TITLE
Fatal error at installation when executing "pack info": Server does not allow request for unadvertised object

### ISSUE THREAD

**Issue by ClHg2** [stefan-hoeck/idris2-pack#229]
Expected Output:

```
Package Collection  : nightly-230201
Idris2 URL          : https://github.com/idris-lang/Idris2
Idris2 Version      : 0.6.0
Idris2 Commit       : ad12f8335c4e0fbd532b2c672c17edc88b34f56d
Scheme Executable   : chezscheme
Pack Commit         : b3f8cd2bbdf1fecc749d80f16f1190f56dac45cf
Installed Libraries : base
                      contrib
                      filepath
                      idris2
                      linear
                      network
                      prelude
                      test
                      toml
```

Actual Output:

```
error: Server does not allow request for unadvertised object 698971cbcc7f7ce702a65c0d9af0704b6b727e18
[ fatal ] Error when executing system command.
          Command: "git" "fetch" "-q" "origin" "698971cbcc7f7ce702a65c0d9af0704b6b727e18"
          Error code: 1
```

I tried to search "698971cbcc7f7ce702a65c0d9af0704b6b727e18" in the directory `~/.pack/.cache` and I found it in two files:

`git/github.com/stefan-hoeck/idris2-pack-db/collections/nightly-230201.toml`:

```toml
[db.barbies]
type        = "github"
url         = "https://github.com/stefan-hoeck/idris2-barbies"
commit      = "698971cbcc7f7ce702a65c0d9af0704b6b727e18"
ipkg        = "barbies.ipkg"
packagePath = false
```

and `git/github.com/stefan-hoeck/idris2-pack-db/STATUS.md`

```markdown
[barbies](https://github.com/stefan-hoeck/idris2-barbies) | Barbies: Data types that can change their clothes | [698971c](https://github.com/stefan-hoeck/idris2-barbies/commit/698971cbcc7f7ce702a65c0d9af0704b6b727e18) 
```

So I changed my directory to `~/.pack/.cache/git/github.com/stefan-hoeck/idris2-barbies` and executed 'pack info' again, and then it worked.

Operating System: Ubuntu 20.04.
