### ISSUE TITLE
install script cannot work under CI

### ISSUE THREAD

**Issue by dannypsnl** [stefan-hoeck/idris2-pack#251]
GitHub Action file:

```yaml
    steps:
      - uses: Bogdanp/setup-racket@v1.10
        with:
          architecture: "x64"
          distribution: "full"
          variant: "CS"
          version: "stable"
      - name: install idris2-pack
        run: |
          set -o pipefail
          bash -c "$(curl -fsSL https://raw.githubusercontent.com/stefan-hoeck/idris2-pack/main/install.bash)"
          echo "$HOME/.pack/bin" >> $GITHUB_PATH
          source $HOME/.profile
      - uses: actions/checkout@v3
      - name: Test
        run: pack test idris2-library
```

I'm expecting this will work, but in fact it will fail at:

```shell
read -r -p 'Enter the name of your chez-scheme or racket binary [racket]: ' SCHEME
Error: Process completed with exit code 1.
```

Do you know any proper way to avoid trigger `read` command or will need to modify the install script?
