### ISSUE TITLE
Installing local pack with pack does not work

### ISSUE THREAD

**Issue by trevarj** [stefan-hoeck/idris2-pack#59]
From within the `idris2-pack` repo, running the following command corrupts the current `pack` installation:

```bash
# inside idris2-pack/
$ pack install-app pack.ipkg
```

Is there a correct way to install a local version without bootstrapping with `micropack` and having to recompile everything?

For now I will just modify symlinks.

**Comment by stefan-hoeck** [comment]
You can override the "official" pack version to use in your `.pack/user/pack.toml` file. For instance, after entering the following line to your `pack.toml` file, pack should use your local version of pack when using package collection `nightly-220525`:

```toml
[custom.nightly-220525.pack]
type = "local"
path = "/pach/to/pack"
ipkg = "pack.ipkg"
```

If you want to use your local pack repository with all package collections, add the following to `.pack/user/pack.toml`:

```toml
[custom.all.pack]
type = "local"
path = "/pach/to/pack"
ipkg = "pack.ipkg"
```

Does this solve your issue?
